---
name: Docker image
on:
  push:
    branches:
      - main
      - 'py-*'
  workflow_dispatch:

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     username: tobix
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Detect image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tobix/pywine
          tags: |
            type=raw,value=latest
            type=raw,value=3.12

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
