---
name: Update Docker Hub Description
on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - README.md
  #     - .github/workflows/hub-description.yaml
  workflow_dispatch:
    inputs:
      repository:
        description: 'Docker repository'
        required: true
      username:
        description: 'Docker Hub username'
        required: true

permissions:
  contents: read

jobs:
  description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ github.event.inputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.event.inputs.repository }}
          short-description: ${{ github.event.repository.description }}
